language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/golang/dep/...
  - go get github.com/mattn/goveralls
install:
  - $GOPATH/bin/dep ensure
script:
  - $GOPATH/bin/goveralls -service=travis-ci
